spring.application.name=cloudGateway

# Logs internes du Gateway
logging.level.org.springframework.cloud.gateway=DEBUG

# Logs du client WebFlux qui fait le proxy vers le backend
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=DEBUG
