spring.application.name=cloudGateway

# Logs internes du Gateway
logging.level.org.springframework.cloud.gateway=DEBUG

# Logs du client WebFlux qui fait le proxy vers le backend
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=DEBUG
logging.level.org.springframework.security=DEBUG

#api prefix
api.prefix=/api/v1
  #/api/v1

springdoc.api-docs.enabled=true
# swagger-ui
springdoc.swagger-ui.path=/doc

# Liste des microservices
springdoc.swagger-ui.urls[0].name=infosPatients
springdoc.swagger-ui.urls[0].url=/api/v1/patient/v3/api-docs

springdoc.swagger-ui.urls[1].name=notesPatient
springdoc.swagger-ui.urls[1].url=/api/v1/patient/note/v3/api-docs


springdoc.swagger-ui.urls[2].name=riskPatients
springdoc.swagger-ui.urls[2].url=/api/v1/patient/risk/v3/api-docs

