spring.application.name=cloudGateway

# Logs internes du Gateway
logging.level.org.springframework.cloud.gateway=INFO

# Logs du client WebFlux qui fait le proxy vers le backend
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=INFO
logging.level.org.springframework.security=INFO

#api prefix
api.prefix=${API_PREFIX:/api/v1}

####################jwt secret###########
jwt.secret=${JWT_SECRET}


##################url services#######################
service.infospatient.url=${SERVICE_INFOS_PATIENT_URL}
service.notespatient.url=${SERVICE_NOTES_PATIENT_URL}
service.riskpatient.url=${SERVICE_DIABETES_RISK_PATIENT_URL}
frontend.url=${FRONTEND_URL}



springdoc.api-docs.enabled=true
# swagger-ui
springdoc.swagger-ui.path=/doc

#springdoc.api-docs.path=/gateway/v3/api-docs

# Liste des microservices
springdoc.swagger-ui.urls[0].name=${SWAGGER_SERVICE_INFOS_PATIENT_NAME:infosPatient}
springdoc.swagger-ui.urls[0].url=${SWAGGER_SERVICE_INFOS_PATIENT_URL:/api/v1/patient/v3/api-docs}

springdoc.swagger-ui.urls[1].name=${SWAGGER_SERVICE_NOTES_PATIENT_NAME:notesPatient}
springdoc.swagger-ui.urls[1].url=${SWAGGER_SERVICE_NOTES_PATIENT_URL:/api/v1/patient/note/v3/api-docs}


springdoc.swagger-ui.urls[2].name=${SWAGGER_SERVICE_DIABETES_RISK_PATIENT_NAME:riskPatient}
springdoc.swagger-ui.urls[2].url=${SWAGGER_SERVICE_DIABETES_RISK_PATIENT_URL:/api/v1/patient/risk/v3/api-docs}

springdoc.swagger-ui.urls[3].name=${SWAGGER_SERVICE_GATEWAY_NAME:gateway}
springdoc.swagger-ui.urls[3].url=${SWAGGER_SERVICE_GATEWAY_URL:/v3/api-docs}

